### ISSUE TITLE
Race-condition that can rarely happen

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#100]
http://mongodb.github.io/node-mongodb-native/api-generated/collection.html#findandmodify

Update flow is this:
1. We first fetch the ids with {foo: false} (X ids)
2. We execute update
3. We send X messages to "collectionName" channel, and 1..X messages to "collectionName::_id" channel

If the insertion happens between 1 and 2. Redis will not notify the watchers that {bar: true}.

**Comment by raphaelarias** [comment]
We're implementing redis-oplog once again. But we are having a very strange behaviour.

We use findAndModify to have unique numbers for some entities.

Without using RedisOplog, it works just fine.

But when we activate it, we get the same number twice, for example:
I insert a document (in a hook, before the insert we findAndModify to get the number). It works just fine, then we insert another document. The number is the same.

We've added some console.log, and we can see that the mongo successfully updated the collection, so it should be returning the up-to-date number.

PS: Every second document we add it returns the proper number.

Do you think it could be related to this issue?

Our findAndModify
`const response = Promise.await(Counters.rawCollection().findAndModify(
      { organizationId },
      [],
      { $inc: { [type]: step } },
      { new: true, upsert: true, fields: { [type]: true } },
    ));`

Response:
` lastErrorObject: { updatedExisting: true, n: 1 }, value: { _id: 'r22cNzHgeF3sDKSAa', student: 620 }, ok: 1 } { _id: { _str: '5aa3ce19e153ef735b9b8c54' },`

Screenshot:

<img width="254" alt="screen shot 2018-04-02 at 2 33 52 pm" src="https://user-images.githubusercontent.com/5008166/38183332-02dcd91c-3683-11e8-872a-a3f89da3ad36.png">

**Comment by raphaelarias** [comment]
It does make sense. I'll try to create a repo to reproduce the problem, because, as soon as i uninstall redis-oplog we stop having duplicated counter.

**Comment by theodorDiaconu** [comment]
@raphaelarias keep in mind that we currently do not have support for .rawCollection() methods.

**Comment by raphaelarias** [comment]
Ok. I can't think why redis-oplog would influence the behaviour of a rawCollection methods. We tried moving the package position in the packages file, but it does not work.

Because we don't use publications for findAndModify (I think it does not even work) but the method still works erratically when we use with redis-oplog. But let me go deeper on this issue. Maybe it's not with redis-oplog and i'm correlating things incorrectly.

I'm just puzzled because it happened when we added, and stopped when we removed the package. And we really need it.

**Comment by theodorDiaconu** [comment]
@raphaelarias best would be to create a reproduction repo quickly to show-case this... otherwise it's hard for me to help you

**Comment by raphaelarias** [comment]
Yep. I'm doing that. o/\o

**Comment by adammoisa** [comment]
Hi, I'm running into a similar problem here. We have a unique case where we absolutely must use bulk operations in general. For some operations in the app I can deff switch to Meteor update methods in a loop so the event would work with Optimistic UI and the RedisOplog package (you rock btw), but it would be significantly less efficient for most cases. Right now we're getting the flicker error, where I see it change and then change back since the validation from the server side of the method never returned.

Is there any way to manually trigger the publication or thread directly after the `bulkWrite` (or any call to a `rawCollection()` method) is complete in it's callback? It would be a very elegant solution for me as I can individually update channels based on successful writes or custom conditions, but I need some sort of manual method. Maybe there's a way to fake-mirror the changes up to Redis?

**Comment by theodorDiaconu** [comment]
@adammoisa read here: https://github.com/cult-of-coders/redis-oplog/blob/master/docs/outside_mutations.md
