### ISSUE TITLE
Benefits or remedies

### ISSUE THREAD

**Issue by janat08** [cult-of-coders/redis-oplog#171]
What makes this better than mongo oplog? I imagine you still want the RAM for every meteor instance, but now on separate machine. I imagine you may still keep the oplog around on mongo anyhow if you scale to substitute basic oplog.

**Comment by theodorDiaconu** [comment]
The real advantage is that you gain control over reactivity and you can fine-tune it.
As in you can do updates that do not trigger reactivity, or updates that trigger reactivity on a specific namespace.

Take the scenario where you have messages collection, organized by a threadId.
If you want to reactively watch all messages for threadId using the standard way, every instance would receive every message update oplog, meaning scaling becomes impossible after a point because every node process will try to make sense out of every message sent.

**Comment by janat08** [comment]
Mongo is getting native subscriptions called messages or something, in 3.6.

**Comment by theodorDiaconu** [comment]
@janat08 that would be great, but it depends on the level of depth they go in.

**Comment by evolross** [comment]
BTW This is a good article on why `redis-oplog` is needed: [https://www.compose.com/articles/connecting-to-the-oplog-on-the-new-mongodb/](url)

**Comment by janat08** [comment]
url isn't working, and mongo is looking to replace meteor reactivity exactly with said messages.

**Comment by theodorDiaconu** [comment]
@janat08 it's not that easy... mongo is the database, the client doesn't communicate with the database directly, a huge part of Meteor's reactivity will still be in there, most likely they will replace the oplog tailing component.  

To make the url work copy/paste it in the browser. If you read it you understand why redis-oplog is needed as @evolross said

**Comment by evolross** [comment]
URL fixed.  Read the "Why Oplog?" section of the article.
