### ISSUE TITLE
Possible that Vent fires messages twice?

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/redis-oplog#294]
Hey @theodorDiaconu,
I'm just sending temporary messages via Vent and have an issue within our WebRTC application. We use Vent to send signaling messages between clients. Sometimes it happens, that messages are sent twice. So I got the following in our logs:

    [Log] {type: "call.accepted", data: null, fromUserId: "A5SCZA6FFSJcNt8yv"}
    [Log] {type: "call.accepted", data: null, fromUserId: "A5SCZA6FFSJcNt8yv"}

If that happens, it is not possible to establish a connection between both clients. I've already implemented something like this in our "accept" function:

```
  if(!this.acceptedCall) {
            this.acceptedCall = true;
            rtcChatHelper.acceptCall(this.foreignCall()); // Sends the Vent message
        }
```

The error still occurs, so I'm wondering if there is an issue with Vent?

// Edit: I'll try to add a random string into the data object, so I can check if the error happens because the user clicked twice (different strings) on the button or if we got the same message twice (same string).

**Comment by dnish** [comment]
Yep, it's an issue with Vent:

<img width="764" alt="bildschirmfoto 2018-07-12 um 14 41 56" src="https://user-images.githubusercontent.com/7636313/42633791-d132aa28-85e1-11e8-8255-3814191cc262.png">

As you can see, the message was sent twice with the same random string.

**Comment by dnish** [comment]
Seems like an issue within our application, we've created the Vent listener within the onCreated event of a Blaze template which is not a good idea (because the user may switch sites and so we'll have several listeners at the same time).

**Comment by evolross** [comment]
Had the same issue. You can add a listener fine in the `onCreated` of a Blaze template.  Just make sure to stop it in the `onDestroyed` and you won't get duplicate listeners:
```
Template.someTemplate.onDestroyed(function() {
  let instance = this;

  //  Kill the Redis Vent listener
  instance.someListener.stop();
});
```
One gotcha I've found is putting Vent listeners in the `onCreated` of templates may not be the best approach because depending on if that template was instantiated or not, it may _miss_ the Vent emission coming from wherever it originated.  Depending on your use-case, this can be problematic. Because Vent emissions aren't queued up until they're received.  They're "fire and forget", so you either receive them or miss them.

This led me to putting all the logic for lots of various types of Vent messages in one big `instance.someListener.listen(function(response) {...});` function on the _top-level_ parent template.  I then just `if/else` the contents of the `response` object in order to update various things (versus having a bunch of different listeners). Incoming Vent emissions store values in ReactiveVars that belong to the top-level template. Any sub-templates that need Vent updates receive them by autorun-listening to a top-level ReactiveVar that is set by the incoming Vent emissions in the top-level template.

Not sure if this is the best pattern, but this is working for me.  I have a whole micro-service that is used simultaneously by thousands of users that is completely pub-sub free and only uses Vent emissions to work. Super light-weight.  Working good so far.  It ended up being more involved than I thought using Vent (because I underestimated how much of my micro-service was reactive) but you can successfully implement your own surgically-precise reactivity when needed. Which is very cool.

**Comment by theodorDiaconu** [comment]
@dnish can't you keep it instantiated onCreated and destroy it in onDestroyed ?
