### ISSUE TITLE
Could I use one redis-oplog docker container for multi meteor app?

### ISSUE THREAD

**Issue by thearabbit** [cult-of-coders/redis-oplog#344]
I am a newbie for `Redis-Oplog`.
Could I use one `redis-oplog` docker container for multi meteor app?

**Comment by evolross** [comment]
Yes. You can just set the same `redis` path for each app. As long as the publications don't have the same name it should be fine.

**Comment by thearabbit** [comment]
@evolross thanks for your reply.
My senariyo is:
- I have one `pos-app` (Meteor Point of Sale App)
- I deploy on one server (DigitalOcean) for one company
So it mean that I deploy the same `pos-app` for multi server for multi company
- But use the same `redis-oplog`

Could I use only one `redis-oplog` for the same meteor app?

Please help me, again..

**Comment by evolross** [comment]
Ah, so you have multiple instances of the _same_ app.  You'll probably need to get into doing some custom [namespacing](https://github.com/cult-of-coders/redis-oplog/blob/master/docs/finetuning.md#namespacing) beyond the default channel names that are used when you just use the default Meteor publication code.  Otherwise the publications' channels would end up cross-contaminating with each other on the same redis server.

So if you could somehow insert per-instance naming into the channel names - maybe using environment variables or something from the `settings.json` that is set _per instance,_ they would then not stomp on each other.  Otherwise they would probably each need their own redis server.

**Comment by thearabbit** [comment]
thanks again, but don't understand.
I will try the best, and need you to help me.

**Comment by evolross** [comment]
What don't you understand?

**Comment by thearabbit** [comment]
Now I tried with `multiple redis-oplog` for multi meteor app.
And then I will try `namespacing` later.

**Comment by derwaldgeist** [comment]
Just stumbled upon this. I have a testing and a production server and would like to use the same Redis instance for both of them. It would be neat if one could setup a global namespace in settings.json that would be applied automatically.

**Comment by theodorDiaconu** [comment]
You can use "globalRedisPrefix" :) globalRedisPrefix: "testing", globalRedisPrefix: "production" and it will allow you to keep the same redis servers without collisions.

**Comment by derwaldgeist** [comment]
Oh, that’s awesomw!
