### ISSUE TITLE
Question. Is this applicable to displaying heavy db update from outside of meteor?

### ISSUE THREAD

**Issue by danke02** [cult-of-coders/redis-oplog#350]
Hello.
I use meteor for front-end of my trading system to display book position, P&L, fill list and so on.
Back-end system written in C/JAVA inserts or updates Mongo db documents frequently and heavily.
It gets too slow or irresponsive when market spikes or end of market come close.
As far as I understand, redis-oplog is only useful when mongodb update occurs in meteor by replacing Mongo db's oplog tailing to Redis' pub/sub. In my case, I guess displaying external Mongo db update reactively still requires traditional oplog tailing or polling and can't get benefit from redis-oplog. Something like java-redis-oplog is required to get a benefit. Am I right?

**Comment by evolross** [comment]
You must have missed this section of the documentation - [Outside Mutations](https://github.com/cult-of-coders/redis-oplog/blob/master/docs/outside_mutations.md).

And depending on your front-end templating framework - Blaze, React, etc. - at least with Blaze you'll have issues with the UI keeping up with hundreds or thousands of database updates if they're really coming in that fast. That's more of a design issue and what/how you're using your data and visualizing it. Even with redis-oplog you may still have to fallback to a poll every few seconds, a Meteor Method, or an alternative data-display design because Blaze won't be able to keep up without locking your UI and also possibly your Node event loop. So instead of trying to process thousands of updates, it just polls the data every so often, and can still have a very real-time effect if that's what you're going for.  There's also some throttling settings for Meteor pub-sub that may (or may not) work that well. Probably worth researching. For my app, we had to selectively use polling in certain circumstances. And then other times straight real-time pub-sub works well.

**Comment by danke02** [comment]
> You must have missed this section of the documentation - [Outside Mutations](https://github.com/cult-of-coders/redis-oplog/blob/master/docs/outside_mutations.md).
> 
> And depending on your front-end templating framework - Blaze, React, etc. - at least with Blaze you'll have issues with the UI keeping up with hundreds or thousands of database updates if they're really coming in that fast. That's more of a design issue and what/how you're using your data and visualizing it. Even with redis-oplog you may still have to fallback to a poll every few seconds, a Meteor Method, or an alternative data-display design because Blaze won't be able to keep up without locking your UI and also possibly your Node event loop. So instead of trying to process thousands of updates, it just polls the data every so often, and can still have a very real-time effect if that's what you're going for. There's also some throttling settings for Meteor pub-sub that may (or may not) work that well. Probably worth researching. For my app, we had to selectively use polling in certain circumstances. And then other times straight real-time pub-sub works well.

I definitely missed that article which I should have read.
I use Tabulator which is a javascript table generating library, with minimongo's observechange to display and update DB content. 
Thank you for your advice!
