### ISSUE TITLE
Publish to npm instead of atmosphere

### ISSUE THREAD

**Issue by maxnowack** [cult-of-coders/redis-oplog#52]
This would probably resolve #35
We could rely on meteor globals with this pattern:
````es6
function getMeteorGlobal(packageName, globalName) {
  if (!global.Package || !global.Package[packageName]) return
  return global.Package[packageName][globalName]
}

const Mongo = getMeteorGlobal('mongo', 'Mongo') // from core package
const RedisOplog = getMeteorGlobal('cultofcoders:redis-oplog', 'RedisOplog') // from atmosphere package
````

**Comment by theodorDiaconu** [comment]
Do you have an example of an npm package that is specifically built with Meteor + also has tests built-in ?

**Comment by maxnowack** [comment]
I'll build one ;)

**Comment by theodorDiaconu** [comment]
how would we tackle package dependencies ?

**Comment by theodorDiaconu** [comment]
actually we only depend on : dburles:mongo-collection-instances really, and I use it just to get the collection by a name, I believe that can be solved.

**Comment by maxnowack** [comment]
Here it is: https://github.com/maxnowack/meteor-npm-package
It uses this small package to get globals from meteor: https://github.com/maxnowack/meteor-globals

I think the easiest way to depend on a meteor package would be, to check if the package is there and otherwise log a messagte, throw an exception and kill the process. What do you think?

**Comment by theodorDiaconu** [comment]
Amazing. It's really good, so the only advantage for moving to npm is to offer support for 1.2.x ?

**Comment by maxnowack** [comment]
mainly yes, but it feels like atmosphere is deprecated.

**Comment by gaurav-** [comment]
Just a note that merely moving to npm doesn't automatically mean support for 1.2.x. It would also depend on not using any unsupported Meteor (or its packages') APIs. That would be difficult to control since versions of Meteor packages cannot be controlled through NPM. We might have to rely on unit tests. But I'd worry about it only after the move to npm is complete.

@maxnowack nice initiative with `meteor-globals`! 

For unit testing, there already seems to be supporting packages like https://github.com/Astrocoders/meteor-mocks and https://github.com/meteor-velocity/meteor-stubs. I haven't used them personally though.

**Comment by theodorDiaconu** [comment]
Since this project is meteor related and does not work with the whole ecosystem, until Atmosphere is deprecated it makes no sense to put it to npm. It will lead to unecessary overhead.
