### ISSUE TITLE
Query: can this be dropped into existing project?

### ISSUE THREAD

**Issue by stewartcelani** [cult-of-coders/redis-oplog#72]
I came across this project & Grapher (looks very nice) while looking at GraphQL (apollo). I have an app in beta at the moment and, while I've done some further reading (Meteor thread where https://docs.google.com/document/d/1yo3tRug1cBT1JCKwwSWiUiChuaZjKkY8pGynoszlgx4/edit#heading=h.l3c8qo9fkgu0 is referenced), I would like to know if its safe to drop this into an existing app whilst overriding the publish method?

What performance gains are to be had? Any caveats? Any scenarios you'd recommend about not replacing all your pubs with redis-oplog?

Does this basically tail Mongo's own oplog and serve it from memory instead of via MDG's implementation?

Cheers =)

**Comment by theodorDiaconu** [comment]
@stewartcelani 

I am now in the middle of releasing 1.1 which is going to make it very close to prod-ready
Yes, it works by default with Grapher's reactivity, and yes, Grapher can use the fine-tuning of it because you can modify the $options.

What you should do, is try it, because it's a plug-in, and you can easily disable it. You can help this package become even more robust. 

It doesn't tail the mongo oplog at all. Mongo oplog is dead, it uses Redis to communicate changes throughout the nodes via its pub/sub system.

**Comment by stewartcelani** [comment]
Thanks for the quick response.

I'll install and have a look around in my dev environment and, if things look good, will push it to one of my beta clients (self-hosted on ESXi) with approx. 100-160~ concurrent users over the workday.

Will the performance-increases get tracked by Kadira so I can use previous data as a comparison point?

**Comment by theodorDiaconu** [comment]
@stewartcelani basically if kadira tracks cpu usage then yes :)

**Comment by theodorDiaconu** [comment]
I will close this since the questions have been answered! Cheers.
